### PR TITLE
fix: ignore maxAge if value is empty

### PR DESCRIPTION
**Pull request by fengmk2**

### CODE REVIEW

**Comment by dougwilson** [comment]
Why? Having a cookie with a blank value is valid.

**Comment by dougwilson** [comment]
Ah, what you are saying is that the behavior of this module is a blank value indicates delete. And set max along along with an old expires.

This seems fine. Is is possible to explain why, though. Is just expires not enough or something else?

**Comment by dougwilson** [comment]
Well, looking closer I see what the issue is, actually. Sorry, just wasn't clear at first and there was no explanation 😄

**Comment by dougwilson** [comment]
I will merge and release in about an hour.

**Comment by dougwilson** [comment]
So there wasn't really any previous tests around this behavior, and so I took a deeper look and apparently the way this was written, even the `expires` can be overwritten if explicitly given with an empty cookie value.

So this falls into a strange are on if this is really a bug fix pre se or a suggested change in behavior.

This makes sense why this also moved the conditional down below the `for ... in` loop.

I think the safest thing to do here is to release as `0.8` instead of a patch against `0.7`, as I believe the behavior change makes sense since the method to indicate deleting the cookie is to set the cookie value to fasly, and I can see that one would think that they could still provide the exact same options to the set as a normal set and it would "do the right thing" which is to delete the cookie.

**Comment by fengmk2** [comment]
Still support Node.js 0.8 is hard work today! Great job!

**Pull request merged**
