### PR TITLE
CHIPS Update

### PR DESCRIPTION
**Pull request by matt-neal**
This is a PR to bring this repo up to spec for CHIPS update in Chrome, allowing `partitioned` to be added to the header. It includes automated testing.

### CODE REVIEW

**Comment by XadillaX** [comment]
Hi, should this PR be merged?

**Review by fengmk2 — APPROVED** [review]

**Comment by fengmk2** [comment]
ping @dougwilson

**Comment by dougwilson** [comment]
Looking now 👀

**Comment by dougwilson** [comment]
Ok, I see the docs were added and looks good. I am sorry something came up today, but I will have a new feature release with this and the other items on `master` tomorrow, 12/27 🎉

**Review by dougwilson — APPROVED** [review]

**Pull request merged**
